[project]
name = "tasks-proto"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "celery>=5.6.3",
    "channels>=4.0.0",
    "channels-redis>=4.2.0",
    "django>=5.2.13",
    "django-celery-beat>=2.7.0",
    "django-viewflow>=2.2.12",
    "django-unfold>=0.90.0",
    "flower>=2.0.1",
    "gunicorn>=25.3.0",
    "psycopg2-binary>=2.9.12",
    "python-dateutil>=2.9.0",
    "python-dotenv>=1.1.1",
    "redis>=7.4.0",
    "requests>=2.33.1",
    "uvicorn[standard]>=0.45.0",
    "whitenoise>=6.9.0",
    "django-vite>=3.1.0",
    "dj-email-url>=1.0.6",
    "django-storages>=1.14.0",
    "boto3>=1.42.94",
    "python-magic>=0.4.27",
]

[dependency-groups]
dev = [
    "django-debug-toolbar>=6.3.0",
    "django-extensions>=4.1",
    "factory-boy>=3.3.3",
    "ipython>=9.10.1",
    "pre-commit>=4.6.0",
    "pytest>=9.0.3",
    "pytest-cov>=6.2.1",
    "pytest-django>=4.11.1",
    "ruff>=0.15.11",
]

[tool.ruff.lint]
select = ["F", "I", "T10"]
ignore = []

[tool.ruff.lint.per-file-ignores]
"core/settings/*.py" = ["F405", "F403"]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "core.settings.test"
python_files = ["tests.py", "test_*.py", "*_tests.py"]
addopts = "-v --tb=short --strict-markers"
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "integration: marks tests as integration tests",
]
