# Generated by Django 5.2.6 on 2025-09-21 19:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_processor', '0003_add_nirvana_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=1024),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['nirvana_id'], name='task_proces_nirvana_76df99_idx'),
        ),
    ]
