# Generated by Django 5.2.6 on 2025-09-21 20:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_processor", "0005_item_energy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
