# Generated by Django 5.2.6 on 2025-09-24 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_processor', '0007_tag_item_tags_tag_task_proces_user_id_728123_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminded_at', models.DateTimeField(auto_now_add=True)),
                ('error', models.TextField(blank=True, help_text='Error message if sending failed', null=True)),
                ('nb_retry', models.IntegerField(default=0, help_text='Number of retry attempts')),
                ('active', models.BooleanField(default=True, help_text='Whether to continue retry attempts')),
            ],
            options={
                'ordering': ['-reminded_at'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='remind_at',
            field=models.DateTimeField(blank=True, help_text='Next reminder occurrence', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='rrule',
            field=models.TextField(blank=True, help_text='RRULE recurrence pattern (RFC 5545)', null=True),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['remind_at'], name='task_proces_remind__98ddb3_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['remind_at', 'status', 'is_completed'], name='task_proces_remind__e7b1bb_idx'),
        ),
        migrations.AddField(
            model_name='itemreminderlog',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='task_processor.item'),
        ),
        migrations.AddIndex(
            model_name='itemreminderlog',
            index=models.Index(fields=['item', 'active'], name='task_proces_item_id_1c3814_idx'),
        ),
        migrations.AddIndex(
            model_name='itemreminderlog',
            index=models.Index(fields=['reminded_at'], name='task_proces_reminde_3f8921_idx'),
        ),
    ]
