# Generated by Django 5.2.6 on 2025-09-26 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_processor', '0009_itemreminderlog_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='parent_project',
            new_name='parent',
        ),
    ]
