# Generated by Django 5.2.6 on 2025-09-28 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_processor', '0010_rename_parent_project_item_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='estimated_duration',
            field=models.CharField(blank=True, choices=[('quick', 'Quick (≤2 min)'), ('short', 'Short (15-30 min)'), ('medium', 'Medium (1-2 hours)'), ('long', 'Long (3+ hours)')], help_text='Estimated time duration', max_length=10, null=True),
        ),
    ]
