# Generated by Django 5.2.11 on 2026-03-22 08:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import task_processor.models.document


class Migration(migrations.Migration):
    dependencies = [
        ("task_processor", "0012_fix_collation_version"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=500,
                        upload_to=task_processor.models.document.document_upload_path,
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("file_size", models.BigIntegerField()),
                (
                    "content_type",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="task_processor.item",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["item"], name="task_proces_item_id_683d5b_idx"
                    ),
                    models.Index(
                        fields=["user"], name="task_proces_user_id_edb27b_idx"
                    ),
                    models.Index(
                        fields=["uploaded_at"], name="task_proces_uploade_f2b764_idx"
                    ),
                ],
            },
        ),
    ]
