# Generated by Django 5.2.13 on 2026-07-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_processor", "0014_apikey"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="energy",
            field=models.CharField(
                blank=True,
                choices=[
                    ("high", "High Energy"),
                    ("medium", "Medium Energy"),
                    ("low", "Low Energy"),
                ],
                default=None,
                max_length=10,
                null=True,
            ),
        ),
    ]
