# Generated by Django 5.2.13 on 2026-07-10 09:52

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models

import task_processor.models.email_inbox


class Migration(migrations.Migration):
    dependencies = [
        ("task_processor", "0015_alter_item_energy"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailInbox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        default=task_processor.models.email_inbox.generate_inbox_identifier,
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_inbox",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "email inboxes",
                "permissions": [("use_email_inbox", "Can use the email inbox")],
            },
        ),
        migrations.CreateModel(
            name="AllowedSender",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "inbox",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allowed_senders",
                        to="task_processor.emailinbox",
                    ),
                ),
            ],
            options={
                "ordering": ["email"],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("email"),
                        models.F("inbox"),
                        name="uniq_sender_per_inbox",
                    )
                ],
            },
        ),
    ]
