# Generated by Django 5.2.16 on 2026-07-28 22:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_processor", "0017_create_email_inbox_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="content_hash",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
    ]
