# Generated by Django 5.2.16 on 2026-07-29 15:34
import logging

from django.conf import settings
from django.db import migrations, models
from django.db.models import Count

logger = logging.getLogger(__name__)


def clear_duplicate_hashes(apps, schema_editor):
    """Pre-branch data may hold duplicate (item, content_hash) pairs.

    Keep the hash on the oldest copy and blank it on the others — the
    documents themselves are untouched, they just stay exempt from dedup
    (same treatment as files the backfill could not read).
    """
    Document = apps.get_model("task_processor", "Document")
    duplicated = (
        Document.objects.exclude(content_hash="")
        .values("item_id", "content_hash")
        .annotate(copies=Count("id"))
        .filter(copies__gt=1)
    )
    for group in duplicated:
        extra_ids = list(
            Document.objects.filter(
                item_id=group["item_id"], content_hash=group["content_hash"]
            )
            .order_by("uploaded_at", "id")
            .values_list("id", flat=True)[1:]
        )
        logger.warning(
            "clearing content_hash on duplicate documents %s (item %s)",
            extra_ids,
            group["item_id"],
        )
        Document.objects.filter(id__in=extra_ids).update(content_hash="")


class Migration(migrations.Migration):
    dependencies = [
        ("task_processor", "0019_backfill_document_content_hash"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(clear_duplicate_hashes, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.UniqueConstraint(
                condition=models.Q(("content_hash", ""), _negated=True),
                fields=("item", "content_hash"),
                name="unique_document_content_per_item",
            ),
        ),
    ]
