# Generated by Django 5.2.16 on 2026-07-29 15:36

from django.db import migrations, models

from task_processor.markdown_utils import strip_markdown


def backfill_previews(apps, schema_editor):
    Item = apps.get_model("task_processor", "Item")
    batch = []
    for item in Item.objects.exclude(description="").iterator():
        item.description_preview = strip_markdown(item.description)
        batch.append(item)
        if len(batch) >= 500:
            Item.objects.bulk_update(batch, ["description_preview"])
            batch = []
    if batch:
        Item.objects.bulk_update(batch, ["description_preview"])


class Migration(migrations.Migration):
    dependencies = [
        ("task_processor", "0020_document_unique_document_content_per_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="description_preview",
            field=models.TextField(blank=True, default="", editable=False),
        ),
        migrations.RunPython(backfill_previews, migrations.RunPython.noop),
    ]
