# Generated by Django 5.2.16 on 2026-07-29 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_processor", "0021_item_description_preview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_items",
                to="task_processor.item",
            ),
        ),
    ]
