# Generated by Django 5.2.16 on 2026-08-11 21:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_processor", "0022_alter_item_parent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="nirvana_id",
            field=models.CharField(
                blank=True,
                help_text="External Nirvana ID for syncing",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.UniqueConstraint(
                fields=("user", "nirvana_id"), name="unique_nirvana_id_per_user"
            ),
        ),
    ]
